Added failure callback and exception handling.
serilog-contrib/Serilog.Sinks.Logz.Io pull request #16
Opened 2021-01-02 20:36 UTC by SeppPenner

I have added a try-catch block around the client post and a callback for exceptions, this is quite commonly used in other sinks like this. I hope, it helps :)

2021-06-14 14:04 UTC, Doron-Bargo commented
Hi @mantasaudickas some customers complain on this issue. Can you check this PR?

2021-07-02 06:54 UTC, mantasaudickas requested changes

2022-02-22 15:09 UTC, SeppPenner commented on src/Serilog.Sinks.Logz.Io/LogzioSink.cs
> +                    throw new LoggingFailedException($"Received failed result {result.StatusCode} when posting events to {_requestUrl}");
Sorry for the late reply, I somehow totally missed your comment in my notifications. It's changed now...

2022-02-22 15:18 UTC, SeppPenner commented
Now, it's changed and merged again to be compatible with the current state of the sink.

2022-02-23 14:28 UTC, merged